version = 1

test_patterns = ["*/*_test.go"]

exclude_patterns = ["pkg/crawler/crawler_test.go"]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_path = "github.com/oAGoulart/roedor"

[[analyzers]]
name = "test-coverage"
enabled = true